name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --tag hammadmajeed/flask_demo:1.0
    - name: Checking the built image 
      run:  if docker manifest inspect hammadmajeed/flask_demo:1.0;
            then echo "docker image exists"
            else
              echo "Docker image does not exist"
            fi
    - name: Upload the image
      run: |    
          docker login -u ${{SECRETS.DOCKER_USERNAME}} -p ${{SECRETS.DOCKER_PASSWORD}}
          docker push hammadmajeed/flask_demo:1.0
